cities = (
    ('Ambarlı', 'Ambarlı'),
    ('Armutlu', 'Armutlu'),
    ('Armutlu Tatil Köyü', 'Armutlu Tatil Köyü'),
    ('Avcılar', 'Avcılar'),
    ('Avşa Adası', 'Avşa Adası'),
    ('Bandırma', 'Bandırma'),
    ('Beşiktaş', 'Beşiktaş'),
    ('Bostancı', 'Bostancı'),
    ('Bursa Güzel Yalı', 'Bursa Güzel Yalı'),
    ('Çınarcık', 'Çınarcık'),
    ('Esenköy', 'Esenköy'),
    ('Kadıköy', 'Kadıköy'),
    ('Kartal', 'Kartal'),
    ('Kumla', 'Kumla'),
    ('Marmara Adası', 'Marmara Adası'),
    ('Pendik', 'Pendik'),
    ('Topçular', 'Topçular'),
    ('Tuzla', 'Tuzla'),
    ('Yalova', 'Yalova'),
    ('Yalova Do', 'Yalova Do'),
    ('Yenikapı', 'Yenikapı'),
    ('Armutlu İhlas', 'Armutlu İhlas'),
    ('Avşa Adası', 'Avşa Adası'),
    ('Bursa Mudanya', 'Bursa Mudanya'),
    ('Büyük Çekmece', 'Büyük Çekmece'),
    ('Eminönü', 'Eminönü'),
    ('Erdek', 'Erdek'),
    ('Marmara Adası', 'Marmara Adası'),
    ('Ayvalık', 'Ayvalık'),
    ('Bodrum', 'Bodrum'),
    ('Çeşme', 'Çeşme'),
    ('Chios', 'Chios'),
    ('Fethiye', 'Fethiye'),
    ('Kalymnos', 'Kalymnos'),
    ('Kaş', 'Kaş'),
    ('Kos', 'Kos'),
    ('Kuş Adası', 'Kuş Adası'),
    ('Leros', 'Leros'),
    ('Marmaris', 'Marmaris'),
    ('Meis', 'Meis'),
    ('Midilli', 'Midilli'),
    ('Rodos', 'Rodos'),
    ('Samos', 'Samos'),
    ('Seferhisar', 'Seferhisar'),
    ('Symi', 'Symi'),
    ('Girne', 'Girne'),
    ('Magusa', 'Magusa'),
    ('Mersin', 'Mersin'),
    ('Tasucu', 'Tasucu'),
    ('Tripoli', 'Tripoli'),
)

vehicles = (
    ('Without vehicle', 'Without vehicle'),
    ('Sedan / Salon', 'Sedan / Salon + 30TL'),
    ('Jeep', 'Jeep + 40TL'),
    ('Minibüs', 'Minibüs + 50TL'),
    ('Kamyon', 'Kamyon + 80TL'),
    ('Kamyonet', 'Kamyonet + 100TL'),
    ('Motosiklet', 'Motosiklet + 20TL'),
    ('Otobüs', 'Otobüs + 80TL'),
    ('Römork', 'Römork + 40TL'),
    ('Karavan', 'Karavan + 50TL'),
)
