# Generated by Django 2.0.3 on 2018-04-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Journey',
        ),
    ]
