# Generated by Django 2.0.3 on 2018-04-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180418_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='with_a_car',
        ),
        migrations.AddField(
            model_name='journey',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
