# Generated by Django 2.0.3 on 2018-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180419_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journey',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
