# Generated by Django 2.0.3 on 2018-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20180419_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='departure_city',
            field=models.CharField(choices=[('Ambarlı', 'Ambarlı'), ('Armutlu', 'Armutlu'), ('Armutlu Tatil Köyü', 'Armutlu Tatil Köyü'), ('Avcılar', 'Avcılar'), ('Avşa Adası', 'Avşa Adası'), ('Bandırma', 'Bandırma'), ('Beşiktaş', 'Beşiktaş'), ('Bostancı', 'Bostancı'), ('Bursa Güzel Yalı', 'Bursa Güzel Yalı'), ('Çınarcık', 'Çınarcık'), ('Esenköy', 'Esenköy'), ('Kadıköy', 'Kadıköy'), ('Kartal', 'Kartal'), ('Kumla', 'Kumla'), ('Marmara Adası', 'Marmara Adası'), ('Pendik', 'Pendik'), ('Topçular', 'Topçular'), ('Tuzla', 'Tuzla'), ('Yalova', 'Yalova'), ('Yalova Do', 'Yalova Do'), ('Yenikapı', 'Yenikapı')], default='AMBARLI', max_length=20),
        ),
        migrations.AlterField(
            model_name='journey',
            name='destination_city',
            field=models.CharField(choices=[('Ambarlı', 'Ambarlı'), ('Armutlu', 'Armutlu'), ('Armutlu Tatil Köyü', 'Armutlu Tatil Köyü'), ('Avcılar', 'Avcılar'), ('Avşa Adası', 'Avşa Adası'), ('Bandırma', 'Bandırma'), ('Beşiktaş', 'Beşiktaş'), ('Bostancı', 'Bostancı'), ('Bursa Güzel Yalı', 'Bursa Güzel Yalı'), ('Çınarcık', 'Çınarcık'), ('Esenköy', 'Esenköy'), ('Kadıköy', 'Kadıköy'), ('Kartal', 'Kartal'), ('Kumla', 'Kumla'), ('Marmara Adası', 'Marmara Adası'), ('Pendik', 'Pendik'), ('Topçular', 'Topçular'), ('Tuzla', 'Tuzla'), ('Yalova', 'Yalova'), ('Yalova Do', 'Yalova Do'), ('Yenikapı', 'Yenikapı')], default='AMBARLI', max_length=20),
        ),
    ]
