# Generated by Django 2.0.3 on 2018-04-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_passanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passanger',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
