# Generated by Django 2.0.3 on 2018-04-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20180421_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passanger',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
