# Generated by Django 2.0.3 on 2018-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20180501_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passanger',
            name='vehicle',
            field=models.CharField(choices=[('Without vehicle', 'Without vehicle'), ('Bus + 40TL', 'Bus'), ('Truck + 60TL', 'Truck'), ('Car + 20TL', 'Car')], default='car', max_length=10),
        ),
    ]
