# Generated by Django 2.0.3 on 2016-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20180501_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passanger',
            name='vehicle',
            field=models.CharField(choices=[('Without vehicle', 'Without vehicle'), ('Bus', 'Bus + 40TL'), ('Truck', 'Truck + 60TL'), ('Car', 'Car + 20TL')], default='car', max_length=10),
        ),
    ]
